const courses = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp",
    category: "Web Development",
    difficulty: "Beginner",
    price: 89.99,
    rating: 4.8,
    students: 12450,
    description: "Master modern web development from scratch. Learn HTML, CSS, JavaScript,",
    imageUrl: "public/tq_odv-qtcwv8-spxk-1500w.png",
  },
  {
    id: 2,
    title: "Python for Beginners",
    category: "Data Science",
    difficulty: "Beginner",
    price: 69.99,
    rating: 4.7,
    students: 11567,
    description: "Start your programming journey with Python. Perfect for absolute beginner",
    imageUrl: "public/tq_ywozs8yybf-wtkx-1500w.png",
  },
  {
    id: 3,
    title: "Data Science with Python",
    category: "Data Science",
    difficulty: "Intermediate",
    price: 99.99,
    rating: 4.8,
    students: 11234,
    description: "Complete data science curriculum covering Python, pandas, NumPy,",
    imageUrl: "public/tq_yjxru5ktvs-2k8m-1500w.png",
  },
  {
    id: 4,
    title: "JavaScript Algorithms & Data Structures",
    category: "Web Development",
    difficulty: "Intermediate",
    price: 84.99,
    rating: 4.8,
    students: 9456,
    description: "Master coding interviews with comprehensive coverage of algorithm",
    imageUrl: "public/tq_7migwrur-h-mghe-1500w.png",
  },
  {
    id: 5,
    title: "Advanced React & TypeScript",
    category: "Web Development",
    difficulty: "Advanced",
    price: 129.99,
    rating: 4.9,
    students: 8932,
    description: "Deep dive into React 18 features, TypeScript integration, performance",
    imageUrl: "public/tq_yawjfl1o2u-wrw-1500w.png",
  },
  {
    id: 6,
    title: "React Native Mobile Apps",
    category: "Mobile Development",
    difficulty: "Intermediate",
    price: 109.99,
    rating: 4.7,
    students: 7845,
    description: "Create cross-platform mobile applications using React Native. One",
    imageUrl: "public/tq_5o6ljxiu9w-bo04-1500w.png",
  },
  {
    id: 7,
    title: "UI/UX Design Masterclass",
    category: "Design",
    difficulty: "Intermediate",
    price: 79.99,
    rating: 4.7,
    students: 9123,
    description: "Learn user-centered design, wireframing, prototyping with Figma,",
    imageUrl: "public/tq_agwdr569mp-hf4j-1500w.png",
  },
  {
    id: 8,
    title: "Machine Learning A-Z",
    category: "Data Science",
    difficulty: "Advanced",
    price: 149.99,
    rating: 4.9,
    students: 6789,
    description: "Hands-on machine learning course covering supervised and unsupervise",
    imageUrl: "public/tq_vxkjru_dpw-ksfg-1500w.png",
  },
  {
    id: 9,
    title: "DevOps Fundamentals",
    category: "Cloud Computing",
    difficulty: "Intermediate",
    price: 99.99,
    rating: 4.7,
    students: 6234,
    description: "Learn CI/CD pipelines, Docker, Kubernetes, infrastructure as code, an",
    imageUrl: "public/tq_kfrv0wkj6d-khbh-1500w.png",
  },
  {
    id: 10,
    title: "iOS Development with Swift",
    category: "Mobile Development",
    difficulty: "Beginner",
    price: 94.99,
    rating: 4.6,
    students: 5234,
    description: "Build professional iOS apps from scratch using Swift and SwiftUI.",
    imageUrl: "public/tq_jgi0ug85kg-i0ss-1500w.png",
  },
  {
    id: 11,
    title: "AWS Cloud Architecture",
    category: "Cloud Computing",
    difficulty: "Advanced",
    price: 139.99,
    rating: 4.8,
    students: 5123,
    description: "Master AWS services, design scalable cloud infrastructure, and prepare for",
    imageUrl: "public/tq_8pxypuhl-o-ul1-1500w.png",
  },
  {
    id: 12,
    title: "Design Systems & Components",
    category: "Design",
    difficulty: "Advanced",
    price: 119.99,
    rating: 4.9,
    students: 4123,
    description: "Build scalable design systems, create reusable component libraries, and",
    imageUrl: "public/tq_8h8qh53d26-lm59-1500w.png",
  },
];

const testimonials = [
];